### ISSUE TITLE
Collect eucanetd files from /tmp

### ISSUE THREAD

**Issue by nephomaniac** [eucalyptus/eucalyptus-sosreport-plugins#94]
Opening to discuss collecting eucanetd files from tmp. 
Thanks,
-M
ls -1 /tmp | grep "ips\|ebt\|ipt" | wc -l

In the case of failures files like the following can be generated and could be included in the SOS report,  Example: '/tmp/euca_ipt_file_failed'

Example from eucanetd.log...
2015-08-28 08:10:45 ERROR 000008737 ipt_system_restore       | iptables-restore failed '//usr/lib/eucalyptus/euca_rootwrap iptables-restore -c < /tmp/ipt_file-CExC22': copying failed input file to '/tmp/euca_ipt_file_failed' for manual retry.
2015-08-28 08:10:45 ERROR 000008737 network_driver_implement | could not apply new rules: check above log errors for details

**Comment by quadespresso** [comment]
We may want to capture owner/group/mode of /tmp itself, regardless of euca component.

Earlier this year a customer reported seeing issues after /tmp filled up with files created by eucanetd (a separate issue which has since been fixed). His path to relief was to reformat /tmp, but he neglected to set the perms to be world-writeable. Cue myriad troubles on the frontend, not the least of which was with euca-run-instances and euca-get-credentials. Problem resolved once he corrected the permissions on /tmp.

The above specific issue is being tracked here: https://eucalyptus.atlassian.net/browse/EUCA-10578

**Comment by quadespresso** [comment]
Added commit a708108 to explicitly address the collection of /tmp/euca_*_failed files.
